apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi 
  volumeName: pv-registry-storage
  storageClassName: ""
